### ISSUE TITLE
Why TestRule is in main flavor

### ISSUE THREAD

**Issue by ewoks** [21Buttons/FragmentTestRule#1]
Shouldn't test code be separated from production code? Why both main and androidTest contain same TestRule class?

**Comment by BraisGabin** [comment]
This is a library to test your code. Its *production* code *is* the `FragmentTestRule`.

Why I use the test rule in `androidTest` too? Because I need to test my *production* code.

If you import this library in your code you'll just import the `FragmentTestRule`.

I must write the README and publish it in maven central... I hope I can do it soon.

Any feedback is more than welcome :)
